ALTER TABLE users ADD COLUMN  `gender` VARCHAR(50);
ALTER TABLE users ADD COLUMN  `mobile` VARCHAR(50);
ALTER TABLE users ADD COLUMN  `image` VARCHAR(50);
ALTER TABLE users ADD COLUMN  `status` VARCHAR(50);
ALTER TABLE users ADD COLUMN  `designation` VARCHAR(50);